"""Fabric scripts.

Require mkvirtualenv to  be installed on all machines and  to be run in,
and WORKON_HOME defined in .bash_profile.

This is configured for Ubuntu systems.

"""
from __future__ import with_statement
import os

from fabric.api import *

env.project = "h1ds"
env.git_url = "git://code.h1svr.anu.edu.au/h1ds/h1ds.git"
env.moin_dl_url = "http://static.moinmo.in/files/moin-1.9.3.tar.gz"
## TODO: use introspection to get python dir for venv.


def dev():
    """localhost with django dev server"""
    env.environment = 'development'
    env.mkvirtualenv = "mkvirtualenv --distribute --no-site-packages"
    env.hosts = ['localhost']
    env.server_user = 'dave'
    env.server_group = 'dave'

def staging():
    """localhost with apache"""
    env.environment = 'staging'
    env.mkvirtualenv = "mkvirtualenv --distribute --no-site-packages"
    env.hosts = ['localhost']
    env.server_user = 'www-data'
    env.server_group = 'www-data'

def production():
    """h1svr with apache."""
    env.environment = 'production'
    env.mkvirtualenv = "mkvirtualenv -p python2 --no-site-packages --distribute"
    env.user = "datasys"
    env.hosts = ['h1svr']
    env.server_user = 'www-data'
    env.server_group = 'www-data'

def initiate():
    """To be run once only. Non-idempotent."""

    env.venv = "%(project)s_%(environment)s" %env    
    run('%(mkvirtualenv)s %(venv)s' % env)

    with prefix('workon %(venv)s && cdvirtualenv' %env):
        ## Grab the dir so we can use sudo without workon
        env_dir = run('echo $PWD')
        run('git clone %(git_url)s %(project)s' % env)
        run('mkdir -p wiki/data/plugin/theme static log db')
        run('pip install fabric')
    with cd(env_dir):
        sudo('chmod -R ugo+rwX db')
        
def update():
    """Can be run multiple times. Idempotent."""

    env.settings = '%(project)s.settings_%(environment)s' % env
    env.venv = "%(project)s_%(environment)s" %env    
    
    with prefix('workon %(venv)s && cdvirtualenv' %env):
        env_dir = run('echo $PWD')
        
    with cd(env_dir):
        sudo('cp -r %(project)s/moin/underlay wiki' %env)
        sudo('cp %(project)s/conf/h1ds.py wiki/data/plugin/theme' %env)
        sudo('chown -R %(server_user)s:%(server_group)s wiki' %env)
        sudo('chmod -R ug+rwX wiki')
        sudo('chmod -R o-rwX wiki')

    with prefix('workon %(venv)s && cdvirtualenv' %env):
        with prefix('cd %(project)s' %env):
            run("git pull")
            if env.environment == 'development':
                run("./bootstrap.py -d")
            else:
                # TODO: remove the -d flag once git:// access is restored on code.h1svr
                run("./bootstrap.py")
            run('./manage.py syncdb --settings=%(settings)s' % env)
            run('./manage.py collectstatic --settings=%(settings)s' % env)
            run("./manage.py migrate h1ds_core --settings=%(settings)s" % env)
            run("./manage.py migrate h1ds_mdsplus --settings=%(settings)s" % env)
            run("./manage.py migrate h1ds_summary --settings=%(settings)s" % env)
            # run("./manage.py migrate h1ds_configdb --settings=%(settings)s" % env)

    # TODO: shouldn't need to treat environs differently here....
    if env.environment == 'development':
        with prefix('workon %(venv)s && cdvirtualenv && cd %(project)s' %env):
            run("./manage.py loaddata data/mds_testing.json --settings=%(settings)s" % env)
            run("./manage.py loaddata data/summarydb.json --settings=%(settings)s" % env)

    elif env.environment == 'staging':
        # Create Apache config from template
        conf_template = open('%s/h1ds/conf/apache/h1ds_staging.conf.template' %env_dir)
        conf_text = conf_template.read()
        conf_template.close()
        conf_text = conf_text.replace("__venv_dir__", env_dir)
        conf_text = "# DO NOT EDIT THIS FILE DIRECTLY, MAKE CHANGES TO THE TEMPLATE FILE AND RUN fab staging deploy\n"+conf_text
        conf_file = open('%s/h1ds/conf/apache/h1ds_staging.conf' %env_dir, 'w')
        conf_file.write(conf_text)
        conf_file.close()
        # check if we already have a symlink to apache conf
        h1ds_apache_conf = '/etc/apache2/sites-available/h1ds'
        if not os.path.exists(h1ds_apache_conf):
            sudo("ln -s %s/h1ds/conf/apache/h1ds_staging.conf %s" %(env_dir, h1ds_apache_conf))
            sudo("a2ensite h1ds")
        sudo('/etc/init.d/apache2 reload')
    else:
        sudo('/etc/init.d/apache2 reload')
